project:
  type: website
  output-dir: docs

website:
  title: "R Working Group"
  favicon: r_icon.png
  twitter-card: true
  site-url: https://github.com/Oppkey/quarto
  navbar:
    logo: r_logo_rect.png
    right:
      - about.qmd
      - icon: youtube
        href: https://www.youtube.com/rconsortium
      - icon: github
        href: https://github.com/rconsortium
      - icon: twitter
        href: https://twitter.com/rconsortium
      - icon: mastodon
        href: https://fosstodon.org/@RConsortium
    background: light
    foreground: gray
format:
  html:
    theme: slate
    fontsize: 1.5em
    css: quarto/styles.css

editor: visual

